services:
  - type: web
    name: london-no2-app
    env: python
    rootDir: LONDON_NO2_APP  # 👈 ajoute cette ligne
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
